#' Compute sentence weights
#'
#' For a given text and probability distribution, calculates the weights for each sentence
#' @param text A lengthy string of text
#' @param dist A probability distribution, generated by compute_probability_dist()
#' @return A data frame, consisting of the sentences and their weights
#' @import tokenizers
#' @import dplyr
#' @export

sentence_weights <- function(text, dist){
  # For a given text and probability distribution — as returned by compute_probability_dist() — returns the weights for each sentence (the average probability of the words in the sentence)

  sentences <- unlist(tokenize_sentences(text))

  weights <- vector(mode = "numeric")
  for(i in sentences){
    sentence_words <- unlist(tokenize_words(i))
    sentence_probs <- dist %>%
      filter(dist$words %in% sentence_words)
    sentence_weight <- mean(sentence_probs$probs)
    weights <- c(weights, sentence_weight)
  }

  result <- data.frame(sentences, weights, stringsAsFactors = FALSE)
  names(result) <- c("sentences", "weights")
  return(result)

}

